name: Check

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Cache global .gradle folder
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: global-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.kt*') }}
          restore-keys: |
            gradle-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull postgres docker container
        run: docker pull postgres:16

      - name: Pull postgres docker container
        run: docker pull mariadb:11

      - name: Check with Gradle
        run: ./gradlew check
